<a href="https://colab.research.google.com/github/Tanishqfarkya5/Tensorflow/blob/main/Tensorflow_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Defining the constant and variables


In [ ]:
import numpy as np
import tensorflow as tf
tf.__version__

'2.17.0'

In [ ]:
x = tf.constant(([1,2,3],[4,5,6]))
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
print(x.shape)
print(x.dtype)
print(x.numpy())

(2, 3)
<dtype: 'int32'>
[[1 2 3]
 [4 5 6]]


In [ ]:
var = tf.Variable([0.0, 0.0, 0.0])
var.assign([1,2,3])
var
var.assign_add([1,3,5])
var


<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([2., 5., 8.], dtype=float32)>

In [ ]:
print(var.numpy())

[2. 5. 8.]


In [ ]:
A = tf.constant([[3, 4, 5], [1, 4, 6]])
B = tf.constant([[1, 1, 1], [2, 3, 4]])
AB_conc_col = tf.concat([A, B], axis=1)
print(AB_conc_col.numpy())


[[3 4 5 1 1 1]
 [1 4 6 2 3 4]]


In [ ]:
AB_conc_row = tf.concat([A, B], axis=0)
print(AB_conc_row.numpy())


[[3 4 5]
 [1 4 6]
 [1 1 1]
 [2 3 4]]


In [ ]:
t1 = tf.reshape(AB_conc_row,shape=[1,12])
print(t1.numpy())

[[3 4 5 1 4 6 1 1 1 2 3 4]]


In [ ]:
a= tf.constant(2.0)
b = tf.constant(5.0)
c= tf.constant(7.0)
add3 = tf.add(tf.add(a,b),c)
add3.numpy()

14.0

In [ ]:
d= tf.constant(9.0)
e = tf.constant(8.0)
add5 = tf.add(tf.add(d,e),add3)
add5.numpy()

31.0

In [ ]:
x = tf.constant([[3.,4.,5.], [1.,2.,3.]])
y = tf.constant([[7.,8.,9.], [4.,5.,7.]])
add_arr = tf.add(x,y)
print(add_arr.numpy())

[[10. 12. 14.]
 [ 5.  7. 10.]]


In [ ]:
sub = tf.subtract(x,y)
print(sub.numpy())

[[-4. -4. -4.]
 [-3. -3. -4.]]


In [ ]:
mul = tf.multiply(x,y)
print(mul.numpy())

[[21. 32. 45.]
 [ 4. 10. 21.]]


In [ ]:
div = tf.divide(x,y)
print(div.numpy())

[[0.42857143 0.5        0.5555556 ]
 [0.25       0.4        0.42857143]]


In [ ]:
mean_x = tf.reduce_mean(x)
print(mean_x.numpy())

3.0


In [ ]:
mean_x_col = tf.reduce_mean(x,axis=1)
print(mean_x_col.numpy())

[4. 2.]


In [ ]:
mean_x_row = tf.reduce_mean(x,axis=0)
print(mean_x_row.numpy())

[2. 3. 4.]


In [ ]:
a= tf.constant([[10.0,20.0],[30.0,40.0]])
b= tf.constant([[30.0,50.0],[60.0,70.0]])
c= tf.constant([[20.0,40.0],[80.0,90.0]])
sum1 = tf.reduce_sum([a,b,c])
print(sum1.numpy())

540.0


In [ ]:
sum_col = tf.reduce_sum([a,b,c],axis=1)
print(sum_col.numpy())

[[ 40.  60.]
 [ 90. 120.]
 [100. 130.]]


In [ ]:
sum_row = tf.reduce_sum([a,b,c],axis=0)
print(sum_row.numpy())

[[ 60. 110.]
 [170. 200.]]


In [ ]:
A = tf.constant([[2,7],[3,4]])
At = tf.transpose(A)
print(At.numpy())

[[2 3]
 [7 4]]


In [ ]:
v = tf.constant([[5],[8]])
mul = tf.matmul(A,v)
print(mul.numpy())

[[66]
 [47]]


In [ ]:
v = tf.constant([[5, 1 , 4], [8,6, 2], [6,7,8]], dtype=tf.float32)
AD = tf.linalg.det(v)
print(AD.numpy())

198.00002


In [ ]:
vt = tf.transpose(v)
print(vt.numpy())

[[5. 8. 6.]
 [1. 6. 7.]
 [4. 2. 8.]]


In [ ]:
def linear_function():
  x = tf.constant(np.random.randn(3,1))
  w = tf.constant(np.random.randn(4,3))
  b = tf.constant(np.random.randn(4,1))
  y = tf.add(tf.matmul(w,x),b)
  return y
print(linear_function().numpy())

[[ 0.22166159]
 [-0.99449423]
 [-0.73048809]
 [-2.64424579]]


In [ ]:
 def linear_function():
  x = tf.constant(np.random.randn(3,1))
  w = tf.constant(np.random.randn(1,3))
  b = tf.constant(np.random.randn(3,1))
  y = tf.add(tf.matmul(x,w),b)
  return y
print(linear_function().numpy())

[[-1.2625439  -0.73888738 -1.2466265 ]
 [ 0.93842581  1.44295812  0.95376189]
 [ 1.56215357 -1.37027244  1.47301767]]
